### HAL collection response with `_embedded` and collection/item `_links`
GET http://localhost:8080/categories
###
GET http://localhost:8080/categories/1

###
GET http://localhost:8080/categories/details?page=1&size=20

###
POST http://localhost:8080/categories
Content-Type: application/json

{
  "name": "Electronics"
}

###
PUT http://localhost:8080/categories/1
Content-Type: application/json

{
  "name": "Audio"
}

###
DELETE http://localhost:8080/categories/1

###
POST http://localhost:8080/categories
Content-Type: application/json

{
  "name": ""
}

###
POST http://localhost:8080/categories
Content-Type: application/json

{
  "name": "Electronics"
}
