GET http://localhost:8080/categories

###
POST http://localhost:8080/categories
Content-Type: application/json

{
  "name": "Electronics"
}

###
PUT http://localhost:8080/categories/1
Content-Type: application/json

{
  "name": "Audio"
}

###
DELETE http://localhost:8080/categories/1

###
POST http://localhost:8080/categories
Content-Type: application/json

{
  "name": ""
}

###
POST http://localhost:8080/categories
Content-Type: application/json

{
  "name": "Electronics"
}
