GET http://localhost:8080/products
###
POST http://localhost:8080/products
Content-Type: application/json

{
  "name": "Product 1",
  "description": "Description of Product 1",
  "price": 19.99,
  "categoryId": 1
}

###
PUT http://localhost:8080/products/2
Content-Type: application/json

{
  "name": "Product 1 Updated",
  "description": "Updated description",
  "price": 29.99,
  "categoryId": 1
}

###
PATCH http://localhost:8080/products/2
Content-Type: application/json

{
  "price": 19.99
}

###
DELETE http://localhost:8080/products/1

###
GET http://localhost:8080/products/by-category/Electronics

###
GET http://localhost:8080/products/search?name=prod&minPrice=10&maxPrice=100

###
GET http://localhost:8080/products/summaries
